import "./globals.css";

import classNames from "classnames";
import type { Metadata } from "next";
import { Inter, Noto_Sans_JP } from "next/font/google";

import QueryProvider from "@/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  fallback: [],
});

export const notoSansJp = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
  display: "swap",
  fallback: [
    "ヒラギノ角ゴ Pro",
    "Hiragino Kaku Gothic Pro",
    "Osaka",
    "游ゴシック",
    "Yu Gothic",
    "YuGothic",
    "メイリオ",
    "Meiryo",
    "ＭＳ Ｐゴシック",
    "MS PGothic",
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={classNames(
          inter.variable,
          notoSansJp.variable,
          "antialiased",
        )}
      >
        <QueryProvider>
          <div className="flex min-h-screen items-center justify-center bg-slate-50 font-sans">
            <div className="flex min-h-screen w-full max-w-3xl flex-col items-center justify-between bg-white sm:items-start">
              <div className="w-full relative">{children}</div>
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
